---
title: "Percentage of trending videos per category"
author: "Hantang Li"
date: "4/14/2022"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, eval = T)
library(dplyr)
library(plotly)
```

## Interactive plots

```{r, message=FALSE, echo=FALSE, warning=FALSE}
load("df_CA_trending.Rda")
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
df_vid_duration_avg <- df_CA_trending %>%
  filter(likes > 0) %>% 
  filter(views > 0) %>% 
  filter(chunk_vid_duration > 0) %>% 
  group_by(category_name, year) %>% 
  summarise(across(c(chunk_vid_duration, views, likes), mean, na.rm = TRUE))

df_vid_duration_count <- df_CA_trending %>%
  group_by(category_name, year) %>% 
  count()

df_vid_count_duration_avg <- merge(df_vid_duration_avg, df_vid_duration_count)

df_vid_count_duration_avg$category_name <- replace(df_vid_count_duration_avg$category_name, df_vid_count_duration_avg$category_name=="29", "Nonprofits & Activism")

# Normalize count
num_videos_2017 <- count(df_CA_trending[df_CA_trending$year=="2017",])
num_videos_2022 <- count(df_CA_trending[df_CA_trending$year=="2022",])

df_vid_count_duration_avg_2017 <- df_vid_count_duration_avg[df_vid_count_duration_avg$year=="2017",]
df_vid_count_duration_avg_2022 <- df_vid_count_duration_avg[df_vid_count_duration_avg$year=="2022",]

df_vid_count_duration_avg_2017$norm_n <- df_vid_count_duration_avg_2017$n / num_videos_2017$n
df_vid_count_duration_avg_2022$norm_n <- df_vid_count_duration_avg_2022$n / num_videos_2022$n

df_vid_count_duration_avg <- rbind(df_vid_count_duration_avg_2017, df_vid_count_duration_avg_2022)
```


# Percentage of trending videos per category

Here I visualized the percentage of the number of videos that belong to each category each year,
you can select to see the popularity of videos each year and compare them.

```{r, message=FALSE, echo=FALSE, warning=FALSE}
p3 <- ggplot(data=df_vid_count_duration_avg, aes(x=reorder(category_name, -n), y=norm_n, colour=year)) +
geom_bar(stat="identity", position=position_dodge())+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ 
  ylab("Percentage of videos in a year")+
  xlab("Category name")+
  ggtitle("Percentage of trending videos per category")
ggplotly(p3)
```
